version: '3.8'

services:

  restful-api:
    image: restful-api-service_1:restful-api_1
    network_mode: bridge
    build:
      context: .
      dockerfile: ./DockerFile.yml
    command: bash -c "python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/code:Z
