FROM ubuntu:16.04 as stage1
FROM python:3
MAINTAINER "Anup Kumar Shrivastaw"
LABEL version="0.0.1"
LABEL maintainer="anupks2009@gmail.com"
ENV PYTHONUNBUFFERED 1
RUN apt-get update && pip install virtualenv && virtualenv --python python3 venv && /bin/bash -c "source venv/bin/activate" && rm -rf /var/lib/apt/lists/*
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/